import { ScoreRing } from '@/components/score-ring'
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Progress } from '@/components/ui/progress'
import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { api } from '@/services/api'
import type { Analysis, SkillMatch } from '@/types/analysis'
import { ArrowRight, BarChart3, Download, FileSearch, Lightbulb, RefreshCw, ShieldAlert, Sparkles } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Cell, Pie, PieChart, ResponsiveContainer, Tooltip } from 'recharts'
import { Link } from 'react-router-dom'

function currentId() { return localStorage.getItem('resumelens-active-analysis') }

export function DashboardPage() {
  const [analysis, setAnalysis] = useState<Analysis | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  useEffect(() => {
    const id = currentId()
    if (!id) { setLoading(false); return }
    api.analysis(id).then(setAnalysis).catch(reason => setError(reason instanceof Error ? reason.message : 'Unable to load the analysis.')).finally(() => setLoading(false))
  }, [])
  if (loading) return <DashboardSkeleton />
  if (!analysis) return <EmptyDashboard error={error} />
  return <Dashboard analysis={analysis} />
}

function Dashboard({ analysis }: { analysis: Analysis }) {
  const chartData = useMemo(() => [{ name: 'Technical', value: analysis.technicalScore, color: '#52525b' }, { name: 'Non-technical', value: analysis.nonTechnicalScore, color: '#a1a1aa' }].filter(item => item.value > 0), [analysis])
  const download = () => {
    const blob = new Blob([JSON.stringify(analysis, null, 2)], { type: 'application/json' })
    const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = `${analysis.resumeName.replace(/\.[^.]+$/, '')}-resumelens-report.json`; link.click(); URL.revokeObjectURL(link.href)
  }
  return <div className="space-y-6">
    <div className="flex flex-col gap-4 border-b pb-6 sm:flex-row sm:items-start sm:justify-between"><div><div className="flex items-center gap-2"><Badge className="bg-emerald-600 text-white hover:bg-emerald-600">{analysis.status.toLowerCase()}</Badge><span className="text-xs text-muted-foreground">{new Date(analysis.analyzedAt).toLocaleString()}</span></div><h1 className="mt-3 text-2xl font-semibold tracking-tight sm:text-3xl">Resume analysis</h1><p className="mt-1 flex items-center gap-2 text-sm text-muted-foreground"><FileSearch className="size-4" />{analysis.resumeName}</p></div><div className="flex gap-2"><Button variant="outline" nativeButton={false} render={<Link to="/" />}><RefreshCw className="size-4" />Re-analyze</Button><Button onClick={download}><Download className="size-4" />Download report</Button></div></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Kpi title="Technical score" value={`${analysis.technicalScore}%`} note="Evidence relevance share" progress={analysis.technicalScore} /><Kpi title="Non-technical score" value={`${analysis.nonTechnicalScore}%`} note="Evidence relevance share" progress={analysis.nonTechnicalScore} /><Kpi title="Technical skills" value={String(analysis.technicalSkills.length)} note="Distinct signals detected" /><Kpi title="Professional skills" value={String(analysis.nonTechnicalSkills.length)} note="Distinct signals detected" /></section>
    <section className="grid gap-6 xl:grid-cols-[0.92fr_1.08fr]"><Card><CardHeader><CardTitle>Classification balance</CardTitle><CardDescription>Scores are calculated from detected evidence relevance, not a claim of candidate quality.</CardDescription></CardHeader><CardContent className="flex flex-col items-center gap-6 sm:flex-row sm:justify-around"><ScoreRing value={analysis.technicalScore} label="Technical" className="text-zinc-700 dark:text-zinc-200" />{chartData.length ? <div className="h-44 w-44"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={chartData} dataKey="value" nameKey="name" innerRadius={46} outerRadius={70} paddingAngle={3}>{chartData.map(item => <Cell key={item.name} fill={item.color} />)}</Pie><Tooltip /></PieChart></ResponsiveContainer></div> : <div className="grid size-36 place-items-center rounded-full border text-center text-sm text-muted-foreground">No skill evidence detected</div>}<ScoreRing value={analysis.nonTechnicalScore} label="Professional" className="text-zinc-400 dark:text-zinc-500" /></CardContent></Card>
      <Card><CardHeader><CardTitle className="flex items-center gap-2"><Sparkles className="size-4" />Evidence-led profile</CardTitle><CardDescription>{analysis.explanation.generatedBy}</CardDescription></CardHeader><CardContent><p className="leading-7 text-muted-foreground">{analysis.explanation.summary}</p><div className="mt-5 rounded-lg border bg-muted/30 p-4"><p className="text-sm font-medium">Overall candidate profile</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{analysis.explanation.candidateProfile}</p></div></CardContent></Card></section>
    <section className="grid gap-6 xl:grid-cols-2"><SkillPanel title="Technical skills" description="Technologies, tools, languages, and platforms with source evidence." skills={analysis.technicalSkills} empty="No technical signals were supported by the uploaded resume." /><SkillPanel title="Professional skills" description="Collaboration and working-style signals, shown only when evidence is present." skills={analysis.nonTechnicalSkills} empty="No professional-skill signals were supported by the uploaded resume." /></section>
    <section className="grid gap-6 xl:grid-cols-[1.25fr_0.75fr]"><EvidencePanel analysis={analysis} /><InsightPanel analysis={analysis} /></section>
    <DiagnosticsPanel analysis={analysis} />
  </div>
}

function Kpi({ title, value, note, progress }: { title: string; value: string; note: string; progress?: number }) { return <Card><CardContent className="p-5"><p className="text-sm text-muted-foreground">{title}</p><p className="mt-2 text-3xl font-semibold tracking-tight">{value}</p><p className="mt-2 text-xs text-muted-foreground">{note}</p>{progress !== undefined && <Progress value={progress} className="mt-4" />}</CardContent></Card> }
function SkillPanel({ title, description, skills, empty }: { title: string; description: string; skills: SkillMatch[]; empty: string }) { const groups = Object.entries(skills.reduce<Record<string, SkillMatch[]>>((accumulator, item) => { (accumulator[item.category] ??= []).push(item); return accumulator }, {})); return <Card><CardHeader><CardTitle>{title}</CardTitle><CardDescription>{description}</CardDescription></CardHeader><CardContent>{groups.length ? <div className="space-y-5">{groups.map(([category, items]) => <div key={category}><p className="mb-2 text-xs font-medium uppercase tracking-[0.12em] text-muted-foreground">{category}</p><div className="flex flex-wrap gap-2">{items.map(skill => <Badge key={skill.skill} variant="secondary" className="px-2.5 py-1 text-sm">{skill.skill}<span className="ml-1.5 text-[10px] text-muted-foreground">{Math.round(skill.relevance * 100)}%</span></Badge>)}</div></div>)}</div> : <p className="rounded-lg border border-dashed p-4 text-sm leading-6 text-muted-foreground">{empty}</p>}</CardContent></Card> }
function EvidencePanel({ analysis }: { analysis: Analysis }) { return <Card><CardHeader><CardTitle>Classification evidence</CardTitle><CardDescription>Expandable excerpts show exactly why a skill was included.</CardDescription></CardHeader><CardContent><Accordion className="w-full">{analysis.evidence.length ? analysis.evidence.map((item, index) => <AccordionItem key={`${item.skill}-${index}`} value={`${index}`}><AccordionTrigger className="text-left hover:no-underline"><span className="flex items-center gap-2"><Badge variant={item.classification === 'TECHNICAL' ? 'default' : 'secondary'}>{item.classification === 'TECHNICAL' ? 'Technical' : 'Professional'}</Badge><span>{item.skill}</span></span></AccordionTrigger><AccordionContent><div className="rounded-lg border bg-muted/25 p-3 text-sm leading-6 text-muted-foreground">“{item.text}”<div className="mt-2 text-xs">{item.sourceSection} · relevance {Math.round(item.relevance * 100)}%</div></div></AccordionContent></AccordionItem>) : <p className="text-sm text-muted-foreground">No evidence entries are available.</p>}</Accordion></CardContent></Card> }
function InsightPanel({ analysis }: { analysis: Analysis }) { return <Card><CardHeader><CardTitle className="flex items-center gap-2"><Lightbulb className="size-4" />What the resume communicates</CardTitle></CardHeader><CardContent><Tabs defaultValue="strengths"><TabsList className="w-full"><TabsTrigger value="strengths" className="flex-1">Strengths</TabsTrigger><TabsTrigger value="improve" className="flex-1">Improve</TabsTrigger></TabsList><TabsContent value="strengths" className="space-y-3 pt-3">{analysis.explanation.strengths.length ? analysis.explanation.strengths.map(item => <Insight key={item} text={item} />) : <p className="text-sm text-muted-foreground">Insufficient evidence in the resume.</p>}</TabsContent><TabsContent value="improve" className="space-y-3 pt-3">{analysis.explanation.improvementAreas.map(item => <Insight key={item} text={item} muted />)}</TabsContent></Tabs><div className="mt-5 border-t pt-4"><p className="text-sm font-medium">Technical profile</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{analysis.explanation.technicalProfile}</p><p className="mt-4 text-sm font-medium">Professional profile</p><p className="mt-1 text-sm leading-6 text-muted-foreground">{analysis.explanation.nonTechnicalProfile}</p></div></CardContent></Card> }
function Insight({ text, muted = false }: { text: string; muted?: boolean }) { return <div className="flex gap-3 rounded-lg border p-3 text-sm leading-6"><span className={muted ? 'text-muted-foreground' : 'text-foreground'}>{muted ? <ArrowRight className="mt-1 size-3.5" /> : <Sparkles className="mt-1 size-3.5" />}</span><span>{text}</span></div> }
function DiagnosticsPanel({ analysis }: { analysis: Analysis }) { const data = analysis.diagnostics; return <Card><CardHeader><CardTitle className="flex items-center gap-2"><BarChart3 className="size-4" />Runtime diagnostics</CardTitle><CardDescription>Measured from the current application process at analysis time.</CardDescription></CardHeader><CardContent className="grid gap-4 text-sm sm:grid-cols-2 lg:grid-cols-4"><Metric label="Embedding runtime" value={data.embeddingModel} detail={data.embeddingStatus} /><Metric label="LLM" value={data.llmModel} detail={data.llmStatus} /><Metric label="Analysis duration" value={`${data.analysisDurationMs} ms`} detail={`Extract ${data.documentProcessingTimeMs} ms · classify ${data.inferenceTimeMs} ms`} /><Metric label="JVM heap" value={`${data.usedHeapMb} MB`} detail={`Sampled peak ${data.peakMemoryMb} MB · Max ${data.maxHeapMb} MB`} /></CardContent></Card> }
function Metric({ label, value, detail }: { label: string; value: string; detail: string }) { return <div className="rounded-lg border bg-muted/20 p-4"><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 truncate font-medium" title={value}>{value}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{detail}</p></div> }
function EmptyDashboard({ error }: { error: string | null }) { return <div className="mx-auto max-w-xl py-20 text-center"><span className="mx-auto grid size-12 place-items-center rounded-xl bg-muted"><ShieldAlert className="size-5" /></span><h1 className="mt-5 text-2xl font-semibold">No analysis selected</h1><p className="mt-2 text-muted-foreground">{error ?? 'Upload a PDF or DOCX resume to create an evidence-led analysis.'}</p><Button nativeButton={false} render={<Link to="/" />} className="mt-6">Analyze a resume</Button></div> }
function DashboardSkeleton() { return <div className="space-y-6"><Skeleton className="h-24" /><div className="grid gap-4 md:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-36" />)}</div><div className="grid gap-6 xl:grid-cols-2"><Skeleton className="h-96" /><Skeleton className="h-96" /></div></div> }
